name: deploy CI

on: [push]

jobs:

  deploy:
    name: build and deploy to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist

      - name: Deploy production to Netlify
      - uses: actions/download-artifact@v3
        with:
          name: app-build
      - run: ls dist
      - uses: evnex/netlify-deploy@1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.SITE_ID }}
          build-dir: dist/build
          
